-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Interface.RoleInterface exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onRole : SelectionSet decodesTo API.Object.Role
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo API.Interface.RoleInterface
fragments selections =
    Object.exhuastiveFragmentSelection
        [ Object.buildFragment "Role" selections.onRole
        ]


{-| Can be used to create a non-exhuastive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onRole = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


id : SelectionSet API.ScalarCodecs.Id API.Interface.RoleInterface
id =
    Object.selectionForField "ScalarCodecs.Id" "Id" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecId |> .decoder)


creationDate : SelectionSet API.ScalarCodecs.DateTime API.Interface.RoleInterface
creationDate =
    Object.selectionForField "ScalarCodecs.DateTime" "creationDate" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


modifiedDate : SelectionSet API.ScalarCodecs.DateTime API.Interface.RoleInterface
modifiedDate =
    Object.selectionForField "ScalarCodecs.DateTime" "modifiedDate" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


name : SelectionSet (Maybe String) API.Interface.RoleInterface
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) API.Interface.RoleInterface
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


group : SelectionSet (Maybe Int) API.Interface.RoleInterface
group =
    Object.selectionForField "(Maybe Int)" "group" [] (Decode.int |> Decode.nullable)


priorityLevel : SelectionSet (Maybe Int) API.Interface.RoleInterface
priorityLevel =
    Object.selectionForField "(Maybe Int)" "priorityLevel" [] (Decode.int |> Decode.nullable)
