-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object exposing (..)


type AddCustomer
    = AddCustomer


type AddMember
    = AddMember


type AddProductCategory
    = AddProductCategory


type AddRole
    = AddRole


type Campaign
    = Campaign


type Company
    = Company


type Customer
    = Customer


type Login
    = Login


type NewCampaign
    = NewCampaign


type NewCompany
    = NewCompany


type NewProduct
    = NewProduct


type NewRole
    = NewRole


type Product
    = Product


type ProductCategory
    = ProductCategory


type Role
    = Role


type Signup
    = Signup


type Token
    = Token


type User
    = User
