-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.ScalarCodecs exposing (..)

import API.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    API.Scalar.DateTime


type alias Id =
    API.Scalar.Id


codecs : API.Scalar.Codecs DateTime Id
codecs =
    API.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        }
