-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object.Campaign exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet API.ScalarCodecs.Id API.Object.Campaign
id =
    Object.selectionForField "ScalarCodecs.Id" "Id" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecId |> .decoder)


creationDate : SelectionSet API.ScalarCodecs.DateTime API.Object.Campaign
creationDate =
    Object.selectionForField "ScalarCodecs.DateTime" "creationDate" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


modifiedDate : SelectionSet API.ScalarCodecs.DateTime API.Object.Campaign
modifiedDate =
    Object.selectionForField "ScalarCodecs.DateTime" "modifiedDate" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


name : SelectionSet (Maybe String) API.Object.Campaign
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) API.Object.Campaign
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


product : SelectionSet (Maybe API.ScalarCodecs.Id) API.Object.Campaign
product =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "product" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


platform : SelectionSet (Maybe String) API.Object.Campaign
platform =
    Object.selectionForField "(Maybe String)" "platform" [] (Decode.string |> Decode.nullable)


company : SelectionSet (Maybe API.ScalarCodecs.Id) API.Object.Campaign
company =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "company" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)
