-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object.Company exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet API.ScalarCodecs.Id API.Object.Company
id =
    Object.selectionForField "ScalarCodecs.Id" "Id" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecId |> .decoder)


creationDate : SelectionSet API.ScalarCodecs.DateTime API.Object.Company
creationDate =
    Object.selectionForField "ScalarCodecs.DateTime" "creationDate" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


modifiedDate : SelectionSet API.ScalarCodecs.DateTime API.Object.Company
modifiedDate =
    Object.selectionForField "ScalarCodecs.DateTime" "modifiedDate" [] (API.ScalarCodecs.codecs |> API.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


name : SelectionSet (Maybe String) API.Object.Company
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


email : SelectionSet (Maybe String) API.Object.Company
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


phoneNumber : SelectionSet (Maybe String) API.Object.Company
phoneNumber =
    Object.selectionForField "(Maybe String)" "phoneNumber" [] (Decode.string |> Decode.nullable)


productCategories : SelectionSet decodesTo API.Object.ProductCategory -> SelectionSet (Maybe (List (Maybe decodesTo))) API.Object.Company
productCategories object_ =
    Object.selectionForCompositeField "productCategories" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
