-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object.NewRole exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


ok : SelectionSet (Maybe Bool) API.Object.NewRole
ok =
    Object.selectionForField "(Maybe Bool)" "ok" [] (Decode.bool |> Decode.nullable)


role : SelectionSet decodesTo API.Object.Role -> SelectionSet (Maybe decodesTo) API.Object.NewRole
role object_ =
    Object.selectionForCompositeField "role" [] object_ (identity >> Decode.nullable)
